name: LaTeX Workshop Extension Package
env:
  cache-version: v12
on: [push]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Create extension package
      run: |
        npm ci
        npm run release
    - name: Archive extension package
      uses: actions/upload-artifact@v4
      with:
        name: latex-workshop
        path: latex-workshop-*.vsix